# Generated by Django 3.0.8 on 2020-07-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_workerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workerinfo',
        ),
    ]
